# Model params
model_checkpoint: "checkpoints/postprocessor/"
in_channels: 1
out_channels: 1
patch_size: 96
kernel_size: 3
model_depth: 3
model_width: 4


# Dataset params
dataset_dir: "datasets/"
img_h: 1248
img_w: 960
max_holes: 5

# Train params
batch_size: 128
epochs: 20
lr: 0.01
loss: BCE
seed: 1234